name: MicroTV Bot Run

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 */5 * * *' # हर 5 घंटे में ऑटो रीस्टार्ट होगा

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Tools
      run: |
        pip install requests beautifulsoup4

    - name: Start Telegram Bot
      run: python main.py
      
